name: Deploy Hugo Image to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      DOCKER_HUB_USERNAME: 'danishjoseph'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Log Docker Hub username
        run: |
          echo "Docker Hub username: $DOCKER_HUB_USERNAME"

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/blog .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_HUB_USERNAME/blog
